if(NOT DEFINED PROJECT_ROOT)
    get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

if(NOT DEFINED CONFIG_PATHS)
    set(CONFIG_PATHS
        "config/miner-prod-cp1.local.json"
        "config/miner-prod-cp2.local.json"
        "config/miner-prod-cp3.local.json"
    )
endif()

set(errors "")
set(seen_worker_ids "")
set(seen_node_ids "")

function(add_error msg)
    set(errors "${errors};${msg}" PARENT_SCOPE)
endfunction()

function(read_json_string json key out_var)
    string(REGEX MATCH "\"${key}\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]*)\"" _m "${json}")
    if(CMAKE_MATCH_1)
        set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${out_var} "" PARENT_SCOPE)
    endif()
endfunction()

foreach(cfg_rel IN LISTS CONFIG_PATHS)
    set(cfg_path "${cfg_rel}")
    if(NOT IS_ABSOLUTE "${cfg_path}")
        set(cfg_path "${PROJECT_ROOT}/${cfg_path}")
    endif()

    if(NOT EXISTS "${cfg_path}")
        add_error("Missing config file: ${cfg_path}")
        continue()
    endif()

    file(READ "${cfg_path}" json)

    read_json_string("${json}" "node_id" node_id)
    read_json_string("${json}" "worker_id" worker_id)
    read_json_string("${json}" "payout_address" payout_address)
    read_json_string("${json}" "host" pool_host)
    read_json_string("${json}" "username" pool_username)
    read_json_string("${json}" "password" pool_password)

    if(node_id STREQUAL "")
        add_error("${cfg_path}: node_id is empty")
    endif()
    if(worker_id STREQUAL "")
        add_error("${cfg_path}: worker_id is empty")
    endif()
    if(payout_address STREQUAL "")
        add_error("${cfg_path}: payout_address is empty")
    endif()
    if(pool_host STREQUAL "")
        add_error("${cfg_path}: pool.host is empty")
    endif()
    if(pool_username STREQUAL "")
        add_error("${cfg_path}: pool.username is empty")
    endif()
    if(pool_password STREQUAL "")
        add_error("${cfg_path}: pool.password is empty")
    endif()

    if(payout_address MATCHES "REPLACE_WITH|offline-wallet-placeholder")
        add_error("${cfg_path}: payout_address still contains placeholder")
    endif()
    if(pool_host MATCHES "REPLACE_WITH|127\\.0\\.0\\.1|localhost")
        add_error("${cfg_path}: pool.host is placeholder/local value")
    endif()
    if(pool_username MATCHES "REPLACE_WITH")
        add_error("${cfg_path}: pool.username still contains placeholder")
    endif()
    if(pool_password MATCHES "REPLACE_WITH|^x$")
        add_error("${cfg_path}: pool.password still contains placeholder/default")
    endif()

    if(NOT worker_id STREQUAL "")
        list(FIND seen_worker_ids "${worker_id}" worker_idx)
        if(NOT worker_idx EQUAL -1)
            add_error("${cfg_path}: duplicate worker_id '${worker_id}'")
        else()
            list(APPEND seen_worker_ids "${worker_id}")
        endif()

        string(FIND "${pool_username}" "${worker_id}" worker_in_user_idx)
        if(worker_in_user_idx EQUAL -1)
            add_error("${cfg_path}: pool.username should include worker_id '${worker_id}'")
        endif()
    endif()

    if(NOT node_id STREQUAL "")
        list(FIND seen_node_ids "${node_id}" node_idx)
        if(NOT node_idx EQUAL -1)
            add_error("${cfg_path}: duplicate node_id '${node_id}'")
        else()
            list(APPEND seen_node_ids "${node_id}")
        endif()
    endif()
endforeach()

list(LENGTH errors err_len)
if(err_len GREATER 0)
    message(STATUS "Preflight failed with ${err_len} issue(s):")
    foreach(err IN LISTS errors)
        if(NOT err STREQUAL "")
            message(STATUS " - ${err}")
        endif()
    endforeach()
    message(FATAL_ERROR "Production config preflight failed")
endif()

message(STATUS "Preflight passed: production configs look ready.")