if(NOT DEFINED PROJECT_ROOT)
    get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

if(NOT DEFINED BUILD_DIR)
    set(BUILD_DIR "${PROJECT_ROOT}/build")
endif()

set(missing_items "")
set(warn_items "")

function(require_exists rel)
    if(NOT EXISTS "${PROJECT_ROOT}/${rel}")
        set(missing_items "${missing_items};${rel}" PARENT_SCOPE)
    endif()
endfunction()

function(warn_if_missing rel)
    if(NOT EXISTS "${PROJECT_ROOT}/${rel}")
        set(warn_items "${warn_items};${rel}" PARENT_SCOPE)
    endif()
endfunction()

require_exists("ENTERPRISE_READINESS_REPORT.md")
require_exists(".github/CODEOWNERS")
require_exists("docs/RELEASE_CHECKLIST.md")
require_exists("docs/DRILL_LOG.md")
require_exists(".github/workflows/ci.yml")
require_exists(".github/workflows/soak.yml")
require_exists("scripts/ci-secret-scan.cmake")

warn_if_missing("build/Release/i_mine.exe")
warn_if_missing("build/Release/i_mine_tests.exe")

set(latest_pre_go_live "")
file(GLOB pre_go_live_logs "${PROJECT_ROOT}/logs/pre_go_live_*.log")
if(pre_go_live_logs)
    list(SORT pre_go_live_logs)
    list(GET pre_go_live_logs -1 latest_pre_go_live)
endif()

message(STATUS "============================================================")
message(STATUS "Release Summary Snapshot")
message(STATUS "Project root: ${PROJECT_ROOT}")
message(STATUS "Build dir: ${BUILD_DIR}")
message(STATUS "============================================================")

if(latest_pre_go_live STREQUAL "")
    message(STATUS "Latest pre-go-live log: none found")
else()
    message(STATUS "Latest pre-go-live log: ${latest_pre_go_live}")
endif()

list(LENGTH missing_items missing_len)
list(LENGTH warn_items warn_len)

if(missing_len GREATER 0)
    message(STATUS "")
    message(STATUS "Missing required release artifacts:")
    foreach(item IN LISTS missing_items)
        if(NOT item STREQUAL "")
            message(STATUS " - ${item}")
        endif()
    endforeach()
endif()

if(warn_len GREATER 0)
    message(STATUS "")
    message(STATUS "Warnings (non-blocking):")
    foreach(item IN LISTS warn_items)
        if(NOT item STREQUAL "")
            message(STATUS " - ${item}")
        endif()
    endforeach()
endif()

message(STATUS "")
if(missing_len EQUAL 0)
    message(STATUS "RELEASE SUMMARY: GO (artifact baseline complete)")
    message(STATUS "NOTE: ensure local_quality_check and release_readiness_check were run for this candidate")
else()
    message(STATUS "RELEASE SUMMARY: NO-GO (required artifacts missing)")
    message(FATAL_ERROR "Release summary failed")
endif()
